const { partOne, partTwo } = require('.')
const { input } = require('./input')

test('part 1', () => {
  const testInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

  expect(partOne(testInput)).toBe(14)
})

test('part 1 actual', () => {
  expect(partOne(input)).toBe(413)
})

test('part 2', () => {
  const testInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

  expect(partTwo(testInput)).toBe(34)
})

test('part 2 actual', () => {
  expect(partTwo(input)).toBe(1417)
})
